### PR TITLE
Change PR trigger phrase match criteria

### PR DESCRIPTION
**Pull request by organic-scholar**
Use timeout with phrase match
Use find instead of matches
Change compile target to java8

### CODE REVIEW

**Comment by tuminoid** [comment]
I'm no java expert, but the idea looks good. Preventing lock up by running it in a separate thread for limited time, and also just returning boolean if it hits or not.

My only concern is the 1000ms limit. Have you done some performance testing to see how long does it take to match a long comment with my improved (the one we didn't take in) regex? I would hate to see some false negatives just for the sake of short timeout.

**Comment by organic-scholar** [comment]
Thank you Tuminoid for your input. I have run a couple of tests on some large chunks of text it seems they all executed under 100ms.

**Comment by tuminoid** [comment]
Cool, thanks. It might be different when the server is under load, but that should be fine for 99% of the cases at least. And we can later increase it if it becomes an issue.

**Comment by organic-scholar** [comment]
Yes, that is also an important consideration. In case of a timeout, we are logging the contextual information.

**Review by tuminoid — APPROVED** [review]
LGTM

**Review by toomer — APPROVED** [review]
Looks good.

**Pull request merged**
